These are all the options I need you to script for me:
• Anything in backticks is an option offered by the securtity onion installer.
• Anything in single quotes is a value to be inputted into a field
• Anything ($VARIABLE) is a constant and can be stored in the script for reuse.

Manager
At the end of the manager deployment, run the following:
sudo so-firewall-minion --role=SEARCHNODE --ip=10.10.20.51
And prompt for number of sensors and run firewall rule X number of times based on inputted number of sensors:
sudo so-firewall-minion --role=SENSOR --ip=10.10.20.5[2|3|4|5|6|7]


Search
Deployment state: `Existing Deployment` (Search AND Sensor)
Role: `SEARCHNODE`
Hostname: 'sosearch'
IPv4: '10.10.20.51/24'
Manager hostname: 'somanager'
Manager IP: '10.10.20.50' (if prompted - likely)



Keep default docker ip range: `Yes`
`IP` (how to access web interface)
`Yes`
Single IP range: '10.10.20.0/24' ($VARIABLE)
Review: `Yes`


Do you have any questions about this configuration?