These are all the options I need you to script for me:
• Anything in backticks is an option offered by the securtity onion installer.
• Anything in single quotes is a value to be inputted into a field
• Anything ($VARIABLE) is a constant and can be stored in the script for reuse.

Begin install: `Yes`, then `Install`
Deployment architecture: `Distributed`
Deployment state: `New Deployment` (manager)|`Existing Deployment` (Sensor only)
Role: `MANAGER`
License: 'AGREE'
Network: `Airgap`
Hostname: 'somanager'
Description: <BLANK> (ignore)
Choose NIC (should only be one for manager but two for Sensor)
IP assignment: `STATIC`
Network range: '10.10.20.50/24' ($VARIABLE)
Gateway: '10.10.20.254' ($VARIABLE)
DNS: '10.10.20.253' ($VARIABLE) (need to delete existing 8.8.8.8 and 8.8.4.4)
DNS search domain: `asat.tht`
Keep default docker ip range: `Yes`
Email/Username: `tester@asat.tht`
--PROMPT FOR THIS UPON INITAL STARTING OF SCRIPT--
`IP` (how to access web interface)
`Yes`
Single IP range: '10.10.20.0/24' ($VARIABLE)
Review: `Yes`


Do you have any questions about this configuration?